version: alpha-1
risk:
  single_trade_risk_pct: 0.5
  ruin_floor_drawdown_pct: 15
  loss_streak_brakes:
    n: 7
    safe_mode_at: 14
fees_slippage:
  taker_fee_pct: 0.06
  slip_bps: 2
accounting:
  start_equity: 10000.0
  taker_fee_bps: 6
  slip_bps: 2
